<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

               <!DOCTYPE export [
                  <!-- Declaration de la DTD interne car FireFox ne prends pas en compte les DTDs externes -->
                  <!ELEMENT export (categorie*)>
                     <!ELEMENT categorie (nom, sujet*)>
                        <!ELEMENT nom (#PCDATA)>
                        <!ELEMENT sujet (titre, utilisateur, date, description, reponse*)>
                              <!ELEMENT titre (#PCDATA)>
                              <!ELEMENT auteur (#PCDATA)>
                              <!ELEMENT date (#PCDATA)>
                              <!ELEMENT description (#PCDATA)>
                              <!ELEMENT reponse (utilisateur, date, message)>
                                 <!ELEMENT utilisateur (#PCDATA)>
                                 <!ELEMENT date (#PCDATA)>
                                 <!ELEMENT message (#PCDATA)>

                  <!-- Formatage des caractères spéciaux HTML en XML -->

                  <!ENTITY Ccedil "&#199;">
                  <!ENTITY ccedil "&#231;">
                  <!ENTITY Aacute "&#193;">
                  <!ENTITY aacute "&#225;">
                  <!ENTITY agrave "&#224;">
                  <!ENTITY Agrave "&#192;">
                  <!ENTITY eacute "&#233;">
                  <!ENTITY Eacute "&#201;">
                  <!ENTITY ecirc "&#234;">
                  <!ENTITY Ecirc "&#202;">
                  <!ENTITY nbsp  " ">

               ]><export><categorie><nom>Test</nom><sujet><titre>Apprendre l'algorithmie</titre><utilisateur>CauzYolo</utilisateur><date>2015-01-13</date><description><p>Lel :)<br />&nbsp;</p></description></sujet><sujet><titre>TEST</titre><utilisateur>CauzYolo</utilisateur><date>2015-01-14</date><description>&lt;p&gt;TEST&lt;/p&gt;</description></sujet></categorie></export>