<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

               <!DOCTYPE export [
                  <!-- Declaration de la DTD interne car FireFox ne prends pas en compte les DTDs externes -->
                  <!ELEMENT export (categorie*)>
                     <!ELEMENT categorie (idCat, nom, sujet*)>
                        <!ELEMENT idCat (#PCDATA)>
                        <!ELEMENT nom (#PCDATA)>
                        <!ELEMENT sujet (idSujet, titre, auteur, dateSujet, description, nbVues, estFerme, reponse*)>
                              <!ELEMENT idSujet (#PCDATA)>
                              <!ELEMENT titre (#PCDATA)>
                              <!ELEMENT auteur (#PCDATA)>
                              <!ELEMENT dateSujet (#PCDATA)>
                              <!ELEMENT description (#PCDATA)>
                              <!ELEMENT nbVues (#PCDATA)>
                              <!ELEMENT estFerme (#PCDATA)>
                              <!ELEMENT reponse (idRep, utilisateur, dateReponse, message)>
                                 <!ELEMENT idRep (#PCDATA)>
                                 <!ELEMENT utilisateur (#PCDATA)>
                                 <!ELEMENT dateReponse (#PCDATA)>
                                 <!ELEMENT message (#PCDATA)>

                  <!-- Formatage des caractères spéciaux HTML en XML -->

                  <!ENTITY Ccedil "&#199;">
                  <!ENTITY ccedil "&#231;">
                  <!ENTITY Aacute "&#193;">
                  <!ENTITY aacute "&#225;">
                  <!ENTITY agrave "&#224;">
                  <!ENTITY Agrave "&#192;">
                  <!ENTITY eacute "&#233;">
                  <!ENTITY Eacute "&#201;">
                  <!ENTITY ecirc "&#234;">
                  <!ENTITY Ecirc "&#202;">
                  <!ENTITY nbsp  " ">

               ]><export><categorie><idCat>2</idCat><nom>Reseau</nom><sujet><idSujet>4</idSujet><titre>Apprendre le TCP/IP</titre><auteur>administrateur</auteur><dateSujet>2015-01-04</dateSujet><nbVues>4</nbVues><estFerme>0</estFerme><description>Nous allons commencer par expliquer ces deux protocoles ...</description><reponse><idRep>33</idRep><utilisateur>CauzYolo</utilisateur><dateReponse>2015-01-16</dateReponse><message>[p]TEST[/p]</message></reponse></sujet></categorie></export>